---
- name: Change hosts on /etc/hosts
  hosts: all
  become: true
  tasks:
    - name: Change hosts on /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        content: "10.156.28.20 idm.redhatlab.local\n10.156.28.22 postgre.redhatlab.local\n10.156.28.24 ansible.redhatlab.local\n10.156.28.26 hub.redhatlab.local\n10.156.28.28 execution.redhatlab.local"
    - name: Display the updated contents of /etc/hosts
      command: cat /etc/hosts
      register: hosts_file
    - name: Print the contents of the hosts file
      debug:
        msg: "{{ hosts_file.stdout_lines }}"
