---
- name: This is a play
  hosts: localhost
  tasks:
    - name: Login to OpenShift
      ansible.builtin.command: oc login --insecure-skip-tls-verify --username=developer "https://api.crc.testing:6443" --password=developer
