---
- name: Teste de requisito para execução de setup Red Hat Ansible 
  hosts: all
  become: true
  tasks:
    - name: Check /etc/fstab for noexec
      ansible.builtin.shell: cat /etc/fstab | grep noexec
      register: noexec_check
    - name: Check /etc/fstab for noexec
      ansible.builtin.debug:
        msg: noexec is present in /etc/fstab
      when: noexec_check.stdout | length > 0

#---
#- name: mount point linux
#  hosts: all
#  become: true
#  tasks:
#    - name: Mount -a
#      ansible.builtin.command: mount -a
#    - name: Access mount point /file and cat the readm file
#      ansible.builtin.command: cat /opt/test
#      register: resultado_cat
#    - name: Exibir o resultado
#      debug:
#        var: resultado_cat.stdout
#    - name: Create a file in /file with the name of the linux server
#      ansible.builtin.copy:
#        content: "{{ ansible_hostname }}"
#        dest: /opt/{{ ansible_hostname }}


#---
#- name: A very simple playbook
#  hosts: all
#  become: true
#  tasks:
#    - name: Print effective user running tasks
#      debug: var=ansible_user_id

#    - name: Print kernel release info
#       debug: var=ansible_facts['kernel']

#    - name: Print hostname server
#      debug: var=ansible_facts['nodename']

#    - name: variable playbook test
#      debug: var=ansible_facts['memory_mb']

#    - name: Mount -a
#      ansible.builtin.command: mount -a
      


    
