---
- name: Teste de requisito para execução de setup Red Hat Ansible 
  hosts: all
  become: true
  tasks:
    - name: Print hostname
      ansible.builtin.debug:
        var: ansible_hostname
    - name: Print OS release and version
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: uptime
      ansible.builtin.debug:
        var: ansible_uptime_seconds
    - name: number of cpu
      ansible.builtin.debug:
        var: ansible_processor_count
    - name: List memory in linux
      ansible.builtin.shell: cat /proc/meminfo | grep MemTotal | awk '{print $2/1024/1024 " GB."}'
      register: memory
    - name: output command result
      ansible.builtin.debug:
        msg: "{{ memory.stdout }}"
    - name: Check firewalld status
      ansible.builtin.command: firewall-cmd --state
      register: firewalld_status
    - name: Print firewalld status
      ansible.builtin.debug:
        msg: "{{ firewalld_status.stdout }}"
#    - name: Check noexec in /etc/fstab
#      ansible.builtin.shell: grep noexec /etc/fstab
#      register: check_fstab_result
#      ignore_errors: true
#    - name: Assert that noexec is present
#      ansible.builtin.assert:
#        that: check_fstab_result.stdout is search("noexec")
    - name: list servers from /etc/chrony.conf file
      ansible.builtin.shell: cat /etc/chrony.conf | grep -E "^(server|pool)"
      register: chrony_conf
    - name: output servers
      ansible.builtin.debug:
        msg: "{{ chrony_conf.stdout_lines }}"
    - name: update crypto-policy
      ansible.builtin.command: update-crypto-policies --show
      register: crypto_policy
    - name: Show crypto-policy
      debug:
        var: crypto_policy.stdout
    - name: Alternatives Python
      ansible.builtin.shell: alternatives --list | grep python3
      register: alternatives_python
    - name: Show Alternatives Python
      debug:
        var: alternatives_python.stdout

    - name: SELinux 
      ansible.builtin.command: sestatus
      register: sestatus
    - name: Show SELinux
      debug:
        var: sestatus.stdout

#---
#- name: mount point linux
#  hosts: all
#  become: true
#  tasks:
#    - name: Mount -a
#      ansible.builtin.command: mount -a
#    - name: Access mount point /file and cat the readm file
#      ansible.builtin.command: cat /opt/test
#      register: resultado_cat
#    - name: Exibir o resultado
#      debug:
#        var: resultado_cat.stdout
#    - name: Create a file in /file with the name of the linux server
#      ansible.builtin.copy:
#        content: "{{ ansible_hostname }}"
#        dest: /opt/{{ ansible_hostname }}


#---
#- name: A very simple playbook
#  hosts: all
#  become: true
#  tasks:
#    - name: Print effective user running tasks
#      debug: var=ansible_user_id

#    - name: Print kernel release info
#       debug: var=ansible_facts['kernel']

#    - name: Print hostname server
#      debug: var=ansible_facts['nodename']

#    - name: variable playbook test
#      debug: var=ansible_facts['memory_mb']

#    - name: Mount -a
#      ansible.builtin.command: mount -a
      


    
